name = "state-798-placement-api"
main = "worker.js"
compatibility_date = "2026-09-29"

[[d1_databases]]
binding = "DB"
database_name = "state-798-placement"
database_id = "00000000-0000-0000-0000-000000000000"
